# Generated by Django 2.1.5 on 2019-01-29 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=64)),
                ('status', models.IntegerField(default=0)),
                ('source', models.IntegerField(default=0)),
                ('codimd', models.CharField(max_length=64)),
                ('hide', models.BooleanField(default=False)),
                ('rocket_chat', models.TextField(max_length=64)),
                ('rocket_chat_id', models.TextField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(default='')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('join_code', models.CharField(default='', max_length=256)),
                ('codimd', models.CharField(max_length=64)),
                ('rocket_chat_id', models.TextField(max_length=64)),
                ('rocket_chat_name', models.TextField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
